version:  "3.9"

services:
  nginx_stack:
    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./html/:/usr/share/nginx/html/
    ports:
      - "80:80"
